/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * AI Virtual Health Assistant API
 * OpenAPI spec version: 0.1.0
 */

export interface VitalsInput {
  heartRate: number;
  spo2: number;
  systolicBP: number;
  diastolicBP: number;
  temperature: number;
  fallDetected: boolean;
  /** Number of days the patient has been experiencing symptoms */
  symptomDays?: number;
  /** Whether the patient experiences shortness of breath */
  breathShortness?: boolean;
  /** Whether the patient experiences chest pain or tightness */
  chestPain?: boolean;
  /** Family history of chronic conditions (heart disease, BP, diabetes) */
  familyHistory?: boolean;
}
